// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4h6JC0_lCjnzJryKPaLr_rPnzMGipnyI',
    appId: '1:316527850981:web:1e71e6fc90ea1c9367eb0c',
    messagingSenderId: '316527850981',
    projectId: 'mynotes398',
    authDomain: 'mynotes398.firebaseapp.com',
    storageBucket: 'mynotes398.appspot.com',
    measurementId: 'G-63MNRCH3KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnttGhX3wehX00HxZD3843xFDEV0hZ1Ww',
    appId: '1:316527850981:android:e9e9abfd5fc8fb6267eb0c',
    messagingSenderId: '316527850981',
    projectId: 'mynotes398',
    storageBucket: 'mynotes398.appspot.com',
  );
}
